### ISSUE TITLE
`DenoRuntime.import` is unable to locate modules when used from cli bundled typegate

### ISSUE THREAD

**Issue by Yohe-Am** [metatypedev/metatype#560]
What it says on the tin can. Error is shown here:

![image](https://uploads.linear.app/8a044944-4e60-4301-b1f0-8807e48a5fca/ccb528c8-486f-4f9e-bc55-01fad8bab033/7ab9afcd-6695-4aaf-8b9c-d551f2c36228?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzhhMDQ0OTQ0LTRlNjAtNDMwMS1iMWYwLTg4MDdlNDhhNWZjYS9jY2I1MjhjOC00ODZmLTRmOWUtYmM1NS0wMWZhZDhiYWIwMzMvN2FiOWFmY2QtNjY5NS00YWFmLThiOWMtZDU1MWYyYzM2MjI4IiwiaWF0IjoxNzA1ODU0NjA5LCJleHAiOjMzMjc2NDE0NjA5fQ.jNiRyJ47K4-HtNaJvRccIghETIT0R1fI7PDhMAnSdyc "=588x")

**Comment by zifeo** [comment]
Test

**Comment by zifeo** [comment]
Test

**Comment by zifeo** [comment]
Test
