### ISSUE TITLE
"`tmp` dir does not exist"

### ISSUE THREAD

**Issue by Yohe-Am** [metatypedev/metatype#582]
0.3.3 carries a bug where prisma migrations are broken because the temp dir root isn't created before hand. The `mktmpd` calls don't recursively create the parent directories which is reasonable behavior I suppose. 

A fix would be to either make sure the tmp dir is present at typegate initialization or make all locations where tmp dirs are created recursive. (`mkdir -p` behavior)

**Comment by zifeo** [comment]
@Yohe-Am can the tmp be manually created by the user as a gateway drug or shall increase the priority to highest?
