### ISSUE TITLE
Prevent sdk error outputs after CLI death

### ISSUE THREAD

**Issue by Yohe-Am** [metatypedev/metatype#728]
When loading typegraphs, if the CLI dies for some reason while the sub-process is still alive, the error outputs of the child will pollute the terminal even after the prompt's drawn by the shell. 

Rust panics will drop objects on unwind and it should be possible, between `setsid` and `Drop` implementations to clean them up before exiting. And I mean all descendant processes.

Concretely, the feature on [this](https://github.com/watchexec/process-wrap/issues/6) ticket should be enough to solve it.

**Comment by Yohe-Am** [comment]
Yikes, looks like this is solved after all. Turned out to be an issue with Actix cleanup.

**Comment by Yohe-Am** [comment]
And It's back :/

**Comment by Natoandro** [comment]
This cannot anymore happen now that the child processes do not inherit the standard i/o file descriptors from  the CLI process.
